theme: jekyll-theme-slate
title: Marcin Salamoński
description: Dzielę się wiedzą o programowaniu, linuksie i technologii blockchain. Sprawdź mój profil GitHub: [github.com/marcinsalamonski](https://github.com/marcinsalamonski) oraz
[github.com/ostrykot](https://github.com/ostrykot)
